#!/usr/bin/python3

# Copyright 2025 Benjamin Drung <bdrung@posteo.de>
# SPDX-License-Identifier: ISC

# pylint: disable=invalid-name
# pylint: enable=invalid-name

"""Wrap ansi2html command to take a filename as input."""

import argparse
import gzip
import pathlib
import subprocess
import sys


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command line arguments and return namespace."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-o",
        "--open",
        action="store_true",
        help="Open HTML file afterwards with xdg-open",
    )
    parser.add_argument("ansi_file", type=pathlib.Path)

    args = parser.parse_args(argv)
    if not args.ansi_file.is_file():
        parser.error(f"Not a file: {args.ansi_file}")
    return args


def _read_bytes(path: pathlib.Path) -> bytes:
    raw = path.read_bytes()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return raw


def main(argv: list[str]) -> int:
    """Wrap ansi2html command to take a filename as input."""
    args = parse_args(argv)

    ansi_text = _read_bytes(args.ansi_file)

    html_filename = args.ansi_file.with_suffix(".html")
    with open(html_filename, "wb") as html_file:
        subprocess.run(
            ["ansi2html", "-w"], input=ansi_text, stdout=html_file, check=True
        )

    if args.open:
        subprocess.run(["xdg-open", html_filename], check=True)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))  # pragma: no cover
