#!/bin/bash
set -eu

# Copyright 2022 Benjamin Drung <bdrung@posteo.de>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Generate a Debian source package from a git repository using `git archive`.

TREE_ISH=${1:-HEAD}

if test ! -e debian/changelog; then
	echo "E: debian/changelog not found. You need to run this script in a packaging git branch." >&2
	exit 1
fi

source=$(dpkg-parsechangelog -S Source)
version=$(dpkg-parsechangelog -S Version)
# shellcheck disable=SC2001
upstream_version=$(echo "$version" | sed "s/-[^-]\+$//")
tarball_name="../${source}_${upstream_version}.orig.tar.xz"

if grep -q "^3.0 (quilt)$" debian/source/format 2>/dev/null; then
	# Exclude debian directory when using 3.0 (quilt) source format.
	git_archive_args=(. ':!debian/')
fi

echo "I: git archive --format=tar --prefix=${source}-${upstream_version}/ $TREE_ISH ${git_archive_args[*]} | xz -c -9 >${tarball_name}"
git archive --format=tar --prefix="${source}-${upstream_version}/" "$TREE_ISH" "${git_archive_args[@]}" | xz -c -9 >"${tarball_name}"

echo "I: gpg --output ${tarball_name}.asc --armor --detach-sign --yes ${tarball_name}"
gpg --output "${tarball_name}.asc" --armor --detach-sign --yes "${tarball_name}"
