#!/bin/sh
set -eu

# Copyright 2014-2025 Benjamin Drung <bdrung@posteo.de>
# SPDX-License-Identifier: ISC

# Connect picocom/screen to first ttyUSB device with baud-rate 115200.

device=$(find /dev -maxdepth 1 -name 'ttyUSB*' | sort | head -n 1)

if test -z "$device"; then
    echo "${0##*/}: No /dev/ttyUSB* device found." >&2
    exit 1
fi

if test "${1-}" = "-s"; then
    exec screen "$device" 115200 8N1
else
    # Quitting: Ctrl+a Ctrl+q
    exec picocom -b 115200 "$device"
fi
