---
name: CI

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - debian:bullseye-slim
          - debian:testing-slim
          - debian:unstable-slim
          - ubuntu:jammy
          - ubuntu:kinetic
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          apt-get update &&
          apt-get install --no-install-recommends --yes
          black git isort pylint python3 python3-flake8 python3-jinja2
          python3-publicsuffix2 python3-pygit2 python3-pytest python3-pytest-cov
          python3-unidiff python3-yaml shellcheck
      - name: Run unit tests
        run: python3 -m pytest -ra --cov=. --cov-report=xml tests/
      - name: Install dependencies for Codecov
        run: >
          apt-get install --no-install-recommends --yes
          ca-certificates curl git
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
